title: "Connor M"

# theme                
minimal_mistakes_skin    : "dark" #  "dark", "neon", "mint (light)", "plum (purple)", 

# Reading Files
include:
  - _pages
  - .htaccess
  
collections:
pages:
  output: false #true
  permalink: none #/:path/
  
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single  
  
  
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

use_math: true

# Sass/SCSS
sass:
  sass_dir: _sass

# Outputting
permalink: none

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache




